export const BUSINESS_TRADES = [
  "painting",
  "plumbing",
  "roofing",
  "electrical",
  "landscaping",
  "hvac",
  "general_contractor",
  "house_cleaning",
  "pressure_washing",
  "carpentry",
  "flooring",
  "tile_installation",
  "fence_installation",
  "deck_building",
  "shed_building",
  "concrete_asphalt",
  "tree_service",
  "masonry",
  "siding",
  "shower_glass",
  "stonework",
  "windows",
  "doors",
  "handyman",
] as const;
