import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Clipboard, Download, Loader2 } from "lucide-react";
import { useLocation } from "wouter";
import type { TechnicalSeoScanResult } from "@shared/technicalSeo";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import { buildEmailVersion, buildTechnicalSeoReportModel, truncateReportText } from "./reportModel";
import "./technical-seo-report.css";

interface ScanRecord { id: string; normalizedUrl: string; createdAt: string; status: string; result?: TechnicalSeoScanResult | null }
function Footer({ domain }: { domain: string }) { return <footer className="seo-report-page-footer"><img src="/img/logo-report-footer-mark-20260721-v2.svg?v=20260721-v2" alt="Viva Web Designs" /><span>Local SEO & Technical Audit</span><strong>{domain}</strong></footer>; }
function Header({ number, title }: { number: number; title: string }) { return <header className="seo-report-page-header"><div><span>Evidence-based audit</span><h2>{title}</h2></div><b>{String(number).padStart(2, "0")}</b></header>; }
function gradeClass(grade: string) { return grade === "A" || grade === "B" ? "good" : grade === "C" || grade === "Not assessed" ? "warn" : "bad"; }

export default function TechnicalSeoReportPage({ scanId }: { scanId: string }) {
  const [, navigate] = useLocation(); const { toast } = useToast();
  const { data: scan, isLoading, error } = useQuery<ScanRecord>({ queryKey: [`/api/technical-seo/scans/${scanId}`] });
  if (isLoading) return <div className="flex min-h-[60vh] items-center justify-center gap-2 text-gray-500"><Loader2 className="h-5 w-5 animate-spin" />Preparing report…</div>;
  if (error || !scan?.result) return <div className="mx-auto max-w-xl rounded-xl border bg-white p-8"><h1 className="text-xl font-semibold">Report unavailable</h1><p className="mt-2 text-sm text-gray-600">This report can be generated after the scan completes.</p></div>;
  const report = buildTechnicalSeoReportModel(scan.result); const email = buildEmailVersion(scan.result);
  const date = new Date(report.capturedAt || scan.createdAt).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" });
  const copyEmail = async () => { await navigator.clipboard.writeText(email); toast({ title: "Email version copied" }); };
  const extraPage = report.issues.length > 7;
  return <div className="seo-report-shell"><div className="seo-report-toolbar"><Button variant="outline" onClick={() => navigate(`/admin/tools/technical-seo/${scanId}`)}><ArrowLeft className="mr-2 h-4 w-4" />Back</Button><div><strong>Client audit</strong><span>{report.issues.length} confirmed problems</span></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={copyEmail}><Clipboard className="mr-2 h-4 w-4" />Copy email</Button><Button onClick={() => window.print()}><Download className="mr-2 h-4 w-4" />Save PDF</Button></div></div>
  <main className="seo-client-report-root">
    <section className="seo-report-page seo-report-cover"><div className="seo-report-cover-mark"><img src="/img/logo-header-lockup-20260713-v4.png?v=20260713-header-caption-20-v4" alt="Viva Web Designs" /></div><div className="seo-report-cover-copy"><span>Local SEO & Technical Audit</span><h1>{report.context?.businessName ?? report.domain}</h1><p>{report.context ? `${report.context.trade} · ${report.context.city}, ${report.context.state}` : report.domain}</p></div><div className="seo-report-grade-grid">{report.grades.map((g) => <div className={`grade-${gradeClass(g.grade)}`} key={g.key}><strong>{g.grade}</strong><span>{g.label}</span></div>)}</div><div className="seo-report-cover-meta"><div><span>Website</span><strong>{report.finalUrl}</strong></div><div><span>Audit date</span><strong>{date}</strong></div><div><span>Scope</span><strong>{report.crawl ? `${report.crawl.crawled} pages crawled` : "Legacy one-page scan"}</strong></div></div><Footer domain={report.domain} /></section>
    <section className="seo-report-page"><Header number={2} title="What is broken and why it matters" /><div className="seo-report-summary">{report.summary.map((item) => <p key={item}>{item}</p>)}</div><h3 className="seo-report-section-title">Category grades</h3><div className="seo-report-grade-detail">{report.grades.map((g) => <article key={g.key}><b className={`grade-${gradeClass(g.grade)}`}>{g.grade}</b><div><strong>{g.label}</strong><p>{g.rationale}</p></div></article>)}</div><div className="seo-report-note"><strong>Evidence standard</strong><p>Grades use only completed checks. Unavailable provider data is labeled Not assessed and is not silently scored as a failure. Low grades reflect confirmed conditions.</p></div><Footer domain={report.domain} /></section>
    <section className="seo-report-page"><Header number={3} title="Highest-impact confirmed problems" /><div className="seo-report-issue-list">{report.issues.slice(0, 7).map((issue, i) => <article key={issue.id}><span>{i + 1}</span><div><small>{issue.severity} · {issue.category}</small><h3>{issue.name}</h3><p>{truncateReportText(issue.observation, 220)}</p><p><b>Why it matters:</b> {truncateReportText(issue.rankingImpact ?? issue.interpretation, 240)}</p></div></article>)}</div><Footer domain={report.domain} /></section>
    {extraPage && <section className="seo-report-page"><Header number={4} title="Complete issue register" /><div className="seo-report-compact-issues">{report.issues.slice(7).map((issue, i) => <article key={issue.id}><b>{i + 8}</b><div><small>{issue.severity} · {issue.category}</small><strong>{issue.name}</strong><p>{truncateReportText(issue.observation, 180)}</p></div></article>)}</div><Footer domain={report.domain} /></section>}
    <section className="seo-report-page"><Header number={extraPage ? 5 : 4} title="Measured site, speed, and local evidence" /><div className="seo-report-evidence-grid"><article><h3>Site crawl</h3><p><b>{report.crawl?.crawled ?? 1}</b> pages crawled</p><p><b>{report.crawl?.brokenInternalLinks.length ?? 0}</b> broken internal links</p><p><b>{report.crawl?.thinPages.length ?? 0}</b> thin pages</p><p><b>{report.crawl?.duplicateTitles.length ?? 0}</b> duplicate title groups</p></article><article><h3>Page speed</h3><p>Mobile: <b>{report.performance?.mobile?.score ?? "Not assessed"}</b></p><p>Desktop: <b>{report.performance?.desktop?.score ?? "Not assessed"}</b></p><p>Mobile LCP: <b>{report.performance?.mobile?.lcpMs ? `${Math.round(report.performance.mobile.lcpMs)} ms` : "Not assessed"}</b></p><p>Status: <b>{report.performance?.status.replace("_", " ") ?? "Legacy scan"}</b></p></article><article><h3>Local visibility</h3><p>Organic rank: <b>{report.local?.organicRank ?? "Outside top 10 / not assessed"}</b></p><p>Map rank: <b>{report.local?.mapRank ?? "Outside top 10 / not assessed"}</b></p><p>Profile match: <b>{report.local?.profile?.title ?? "Not matched / not assessed"}</b></p><p>Query: <b>{report.local?.query ?? "Not assessed"}</b></p></article></div><h3 className="seo-report-section-title">Coverage boundaries</h3><div className="seo-report-coverage"><div><strong>Assessed</strong>{report.coverage?.assessed.map((x) => <p key={x}>— {x}</p>)}</div><div><strong>Not assessed</strong>{report.coverage?.notAssessed.map((x) => <p key={x}>— {x}</p>)}</div></div><Footer domain={report.domain} /></section>
    <section className="seo-report-page seo-report-email-page"><Header number={extraPage ? 6 : 5} title="EMAIL VERSION — COPY AND PASTE READY" /><pre>{email}</pre><Footer domain={report.domain} /></section>
  </main></div>;
}
