// Hispanic/Latino name lists for the marketplace name precheck.
//
// SCORING
//   - Recognized Hispanic surname (exact or fuzzy): +70 pts  (passes ≥ 70 alone)
//   - Recognized Hispanic first name (direct or via bridge): +25 pts
//   - Score is capped at 100
//   - spanishOutreachRecommended = score >= 70
//
// HOW TO ADD ENTRIES
//   Add to the raw arrays below in any order, any case, with or without accents.
//   The exported constants are automatically deduplicated, lowercased, and
//   alphabetically sorted at module load time — no manual cleanup required.
//
// ANGLICIZED BRIDGE TABLE
//   Maps common English first-name forms to their Hispanic equivalents.
//   When a first name is not found in HISPANIC_FIRST_NAMES, the scorer checks
//   this table. If the mapped name IS in the list, +25 is awarded.

const RAW_HISPANIC_LAST_NAMES: string[] = [
  // ── A ──────────────────────────────────────────────────────────────────
  "abreu",
  "acevedo",
  "acosta",
  "acuna",
  "agosto",
  "aguayo",
  "aguero",
  "aguilar",
  "aguilera",
  "aguirre",
  "alarcon",
  "alba",
  "alcala",
  "alcaraz",
  "alfaro",
  "alfonzo",
  "alicea",
  "almanza",
  "almazan",
  "almiron",
  "almodovar",
  "alonso",
  "altamirano",
  "alvarado",
  "alvarez",
  "amador",
  "amaya",
  "andrade",
  "angulo",
  "aparicio",
  "apaza",
  "aponte",
  "apushaina",
  "aquino",
  "aragon",
  "arancibia",
  "arango",
  "araque",
  "araujo",
  "araya",
  "arce",
  "arceo",
  "arevalo",
  "arias",
  "aristizabal",
  "armas",
  "armenta",
  "arredondo",
  "arreola",
  "arriaga",
  "arroyo",
  "arteaga",
  "arzola",
  "atencio",
  "avalos",
  "avila",
  "ayala",
  "aymar",
  "ayon",
  "azuaje",
  // ── B ──────────────────────────────────────────────────────────────────
  "baez",
  "barajas",
  "barragan",
  "barraza",
  "barrera",
  "barreto",
  "barrios",
  "batista",
  "bautista",
  "becerra",
  "beltran",
  "benavides",
  "benitez",
  "bermudez",
  "bernal",
  "berrios",
  "blanco",
  "boc",
  "bogado",
  "bonilla",
  "borrego",
  "bravo",
  "briones",
  "brito",
  "bueno",
  "bustamante",
  "bustos",
  // ── C ──────────────────────────────────────────────────────────────────
  "caal",
  "caballero",
  "cabral",
  "cabrera",
  "caceres",
  "cadena",
  "cahuana",
  "caicedo",
  "cal",
  "caldera",
  "calderon",
  "callisaya",
  "camacho",
  "camargo",
  "camilo",
  "campos",
  "canales",
  "canaviri",
  "canizares",
  "cano",
  "cantero",
  "cantu",
  "caraballo",
  "carbajal",
  "cardenas",
  "cardona",
  "cardozo",
  "caro",
  "carrasco",
  "carrillo",
  "carvajal",
  "casas",
  "casillas",
  "castellanos",
  "castillo",
  "castro",
  "catacora",
  "catalan",
  "ccopa",
  "ceballos",
  "cedeno",
  "ceja",
  "centeno",
  "cervantes",
  "chairez",
  "chaparro",
  "chavez",
  "choc",
  "choque",
  "chub",
  "chura",
  "cienfuegos",
  "cifuentes",
  "cisneros",
  "cisternas",
  "coc",
  "collazo",
  "colman",
  "colon",
  "colque",
  "condori",
  "contreras",
  "cordero",
  "cordova",
  "cornejo",
  "coronado",
  "coronel",
  "correa",
  "cortes",
  "cortez",
  "cossio",
  "cotto",
  "cox",
  "coy",
  "cruz",
  "cuadra",
  "cuc",
  "cuevas",
  "cusicanqui",
  "cux",
  // ── D ──────────────────────────────────────────────────────────────────
  "damian",
  "davila",
  "de la cruz",
  "de la fuente",
  "de leon",
  "de los santos",
  "delagarza",
  "delara",
  "deleon",
  "delgadillo",
  "delgado",
  "delosreyes",
  "diaz",
  "dominguez",
  "duarte",
  "dubon",
  "dubón",
  "duenas",
  // ── E ──────────────────────────────────────────────────────────────────
  "echevarria",
  "elizalde",
  "elizondo",
  "encarnacion",
  "enriquez",
  "epieyu",
  "escamilla",
  "escarcega",
  "escobar",
  "escobedo",
  "espinoza",
  "esquivel",
  "estrada",
  "estrella",
  // ── F ──────────────────────────────────────────────────────────────────
  "feliciano",
  "felix",
  "feliz",
  "feria",
  "fernandez",
  "ferreira",
  "fierro",
  "figueroa",
  "fleitas",
  "flores",
  "florez",
  "forero",
  "franco",
  "fuentes",
  // ── G ──────────────────────────────────────────────────────────────────
  "galaviz",
  "galaz",
  "galeano",
  "galindo",
  "gallardo",
  "galvan",
  "gamboa",
  "garay",
  "garcia",
  "garza",
  "gatica",
  "gautier",
  "gaytan",
  "gimenez",
  "giron",
  "godoy",
  "gomez",
  "gonzalez",
  "guaman",
  "guarachi",
  "guardado",
  "guerrero",
  "guevara",
  "guillen",
  "gutierrez",
  "guzman",
  // ── H ──────────────────────────────────────────────────────────────────
  "henriquez",
  "henrriquez",
  "hermosillo",
  "hernandez",
  "herrera",
  "hidalgo",
  "hinojosa",
  "holguin",
  "huaman",
  "huerta",
  "hurtado",
  // ── I ──────────────────────────────────────────────────────────────────
  "ibarra",
  "ical",
  "ich",
  "infante",
  "insfran",
  // ── J ──────────────────────────────────────────────────────────────────
  "jara",
  "jayariyu",
  "jimenez",
  "juarez",
  "justiniano",
  // ── L ──────────────────────────────────────────────────────────────────
  "landa",
  "landeros",
  "lara",
  "lazo",
  "leal",
  "leiva",
  "lema",
  "lemus",
  "leon",
  "lerma",
  "leyva",
  "lezcano",
  "llanque",
  "lopez",
  "lora",
  "lozano",
  "luna",
  // ── M ──────────────────────────────────────────────────────────────────
  "macias",
  "maidana",
  "malagon",
  "maldonado",
  "mamani",
  "mancera",
  "mansilla",
  "maradiaga",
  "mardones",
  "marin",
  "marquez",
  "marrero",
  "marroquin",
  "martinez",
  "matos",
  "mattei",
  "matus",
  "mayorga",
  "mayta",
  "medina",
  "mejia",
  "melendez",
  "membreno",
  "mendez",
  "mendivil",
  "mendoza",
  "meza",
  "mirabal",
  "miranda",
  "molina",
  "monroy",
  "montalvo",
  "montanez",
  "montero",
  "montiel",
  "montoya",
  "mora",
  "morales",
  "moran",
  "morel",
  "moreno",
  "morin",
  "morinigo",
  "muniz",
  "munoz",
  // ── N ──────────────────────────────────────────────────────────────────
  "nail",
  "naranjo",
  "nava",
  "navarrete",
  "navarro",
  "negrete",
  "negron",
  "nunez",
  "nuñez",
  // ── O ──────────────────────────────────────────────────────────────────
  "ocampo",
  "oceguera",
  "ochoa",
  "ojeda",
  "olaya",
  "olazabal",
  "olguin",
  "olivares",
  "olivas",
  "oliveros",
  "olmedo",
  "orellana",
  "ornelas",
  "orozco",
  "ortega",
  "ortigoza",
  "ortiz",
  "ozuna",
  // ── P ──────────────────────────────────────────────────────────────────
  "pabon",
  "pabón",
  "pac",
  "pacco",
  "pacheco",
  "padilla",
  "palacios",
  "palencia",
  "palma",
  "palomino",
  "paredes",
  "parra",
  "patzi",
  "paz",
  "pellot",
  "pena",
  "peralta",
  "perdomo",
  "pereira",
  "perez",
  "peña",
  "pichardo",
  "pietri",
  "pino",
  "pinon",
  "pizarro",
  "poblete",
  "polanco",
  "ponce",
  "pop",
  "portillo",
  "preciado",
  "prieto",
  // ── Q ──────────────────────────────────────────────────────────────────
  "quej",
  "quesada",
  "quevedo",
  "quinones",
  "quintana",
  "quintanilla",
  "quintero",
  "quinteros",
  "quiroga",
  "quiroz",
  "quispe",
  // ── R ──────────────────────────────────────────────────────────────────
  "ramirez",
  "ramos",
  "rangel",
  "recinos",
  "rendon",
  "renteria",
  "resendez",
  "reyes",
  "reyna",
  "rincon",
  "rios",
  "riquelme",
  "rivas",
  "rivera",
  "robledo",
  "robles",
  "rodriguez",
  "rohena",
  "rojas",
  "roldan",
  "roman",
  "romero",
  "rosado",
  "rosales",
  "rosario",
  "rubio",
  "ruiz",
  // ── S ──────────────────────────────────────────────────────────────────
  "saavedra",
  "saenz",
  "salas",
  "salazar",
  "salcedo",
  "saldana",
  "salinas",
  "samaniego",
  "sanchez",
  "sandoval",
  "santana",
  "santiago",
  "santos",
  "segura",
  "sepulveda",
  "serna",
  "serpas",
  "serrano",
  "severino",
  "sic",
  "sigala",
  "silva",
  "solano",
  "solis",
  "soriano",
  "sorto",
  "sosa",
  "soto",
  "suarez",
  // ── T ──────────────────────────────────────────────────────────────────
  "talamantes",
  "tamayo",
  "tapia",
  "taveras",
  "tax",
  "tejada",
  "tejeda",
  "telles",
  "tenorio",
  "teran",
  "terrazas",
  "ticona",
  "tirado",
  "toj",
  "tola",
  "toledo",
  "torrens",
  "torres",
  "trejo",
  "troncoso",
  "trujillo",
  "tun",
  "turcios",
  "tzoc",
  // ── U ──────────────────────────────────────────────────────────────────
  "uc",
  "umanzor",
  "uriana",
  "uriarte",
  "uribe",
  "urrutia",
  // ── V ──────────────────────────────────────────────────────────────────
  "vaca",
  "valadez",
  "valdes",
  "valdez",
  "valdivia",
  "valencia",
  "valenzuela",
  "valle",
  "valverde",
  "vargas",
  "vasquez",
  "vazquez",
  "vega",
  "velarde",
  "velasquez",
  "velazquez",
  "venegas",
  "vera",
  "verduzco",
  "vergara",
  "vidal",
  "villa",
  "villacorta",
  "villalba",
  "villalobos",
  "villanueva",
  "villarreal",
  "villarroel",
  // ── X ──────────────────────────────────────────────────────────────────
  "xol",
  // ── Y ──────────────────────────────────────────────────────────────────
  "yanez",
  "yat",
  "yos",
  "yucra",
  "yupanqui",
  // ── Z ──────────────────────────────────────────────────────────────────
  "zambrano",
  "zamora",
  "zamorano",
  "zapata",
  "zarate",
  "zelaya",
  "zepeda",
  "zertuche",
  "zuniga",
  // ── Portuguese/Brazilian surnames ──────────────────────────────────────
  // Common surnames in Brazil and Portugal that were absent from the
  // Spanish-focused list. Many Brazilian sellers have these names and were
  // scoring 0 despite clearly Latin identity.
  "alves",
  "azevedo",
  "barros",
  "cardoso",
  "carneiro",
  "carvalho",
  "correia",
  "cunha",
  "fernandes",
  "fonseca",
  "freitas",
  "gomes",
  "lima",
  "lopes",
  "mendes",
  "monteiro",
  "moreira",
  "nascimento",
  "nunes",
  "oliveira",
  "pinto",
  "reis",
  "ribeiro",
  "rodrigues",
  "sousa",
  "teixeira",
  "vieira",
];

const RAW_HISPANIC_FIRST_NAMES: string[] = [
  // ── A ──────────────────────────────────────────────────────────────────
  "abdiel",
  "abel",
  "abigail",
  "abner",
  "abril",
  "adan",
  "adrian",
  "adriana",
  "agustin",
  "agustina",
  "aida",
  "ailen",
  "aitana",
  "alan",
  "albert",
  "alberto",
  "aldo",
  "alejandra",
  "alejandro",
  "alexandra",
  "alexis",
  "alfredo",
  "alicia",
  "allan",
  "alma",
  "alonso",
  "amado",
  "amalia",
  "amanda",
  "amaury",
  "amelia",
  "amparo",
  "ana",
  "anderson",
  "andrea",
  "andres",
  "andrew",
  "angel",
  "anita",
  "anthony",
  "antonela",
  "antonella",
  "antonia",
  "antonio",
  "araceli",
  "aracelis",
  "aracely",
  "arcelia",
  "armando",
  "arnulfo",
  "arthur",
  "arturo",
  "ashley",
  "augustin",
  // ── B ──────────────────────────────────────────────────────────────────
  "bautista",
  "beatriz",
  "belen",
  "belkis",
  "benito",
  "benjamin",
  "berenice",
  "bianca",
  "blanca",
  "brayan",
  "brenda",
  "brian",
  "bruno",
  "bryan",
  "bryant",
  "byran",
  "byron",
  // ── C ──────────────────────────────────────────────────────────────────
  "calixto",
  "camila",
  "camilo",
  "candelaria",
  "caridad",
  "carlos",
  "carlos alberto",
  "carmen",
  "carolina",
  "catalina",
  "cecilia",
  "celestino",
  "celia",
  "celina",
  "cesar",
  "charles",
  "charlie",
  "christian",
  "cindy",
  "ciro",
  "citlali",
  "claudia",
  "constanza",
  "consuelo",
  "cristian",
  "cristina",
  "cristobal",
  "crystal",
  // ── D ──────────────────────────────────────────────────────────────────
  "dagoberto",
  "daiana",
  "dalila",
  "damian",
  "daniel",
  "daniela",
  "dario",
  "darwin",
  "david",
  "dayron",
  "deisy",
  "delia",
  "diana",
  "diego",
  "dolores",
  "duvan",
  // ── E ──────────────────────────────────────────────────────────────────
  "eddie",
  "edgar",
  "edmundo",
  "eduardo",
  "edvin",
  "edward",
  "edwin",
  "elena",
  "elias",
  "elisa",
  "eliseo",
  "elizabeth",
  "elmer",
  "elsa",
  "elvira",
  "elvis",
  "emiliano",
  "emilio",
  "emily",
  "emma",
  "emmanuel",
  "encarnacion",
  "enrique",
  "erick",
  "ernesto",
  "esperanza",
  "esteban",
  "ester",
  "evangelina",
  "evelyn",
  "ever",
  // ── F ──────────────────────────────────────────────────────────────────
  "fabian",
  "fabiola",
  "facundo",
  "fatima",
  "fausto",
  "federico",
  "felicia",
  "feliciano",
  "felipe",
  "felix",
  "fermin",
  "fernanda",
  "fernando",
  "ferney",
  "fidel",
  "fiorella",
  "florencia",
  "florencio",
  "florentino",
  "florinda",
  "francisca",
  "francisco",
  "franco",
  "frank",
  "fredy",
  // ── G ──────────────────────────────────────────────────────────────────
  "gabriel",
  "gabriela",
  "gael",
  "genaro",
  "genesis",
  "george",
  "gerardo",
  "german",
  "gilberto",
  "gloria",
  "gonzalo",
  "graciela",
  "guadalupe",
  "guillermo",
  "gustavo",
  // ── H ──────────────────────────────────────────────────────────────────
  "heber",
  "hector",
  "heladio",
  "henry",
  "hernan",
  "hilda",
  "hugo",
  // ── I ──────────────────────────────────────────────────────────────────
  "ignacio",
  "ines",
  "irma",
  "isabel",
  "isabella",
  "isaias",
  "isela",
  "isidro",
  "ismael",
  "israel",
  "itzel",
  "ivan",
  // ── J ──────────────────────────────────────────────────────────────────
  "jacinto",
  "james",
  "javier",
  "javiera",
  "jeison",
  "jennifer",
  "jeremias",
  "jeronimo",
  "jessica",
  "jesus",
  "jesusa",
  "jeyson",
  "jhon",
  "joaquin",
  "joel",
  "johan",
  "john",
  "jonathan",
  "jorge",
  "jose",
  "jose luis",
  "josefa",
  "josefina",
  "joseph",
  "josue",
  "juan",
  "juan carlos",
  "juan cruz",
  "juan david",
  "juan jose",
  "juan pablo",
  "juan sebastian",
  "juana",
  "juanita",
  "julia",
  "julian",
  "julieta",
  "julio",
  // ── K ──────────────────────────────────────────────────────────────────
  "karina",
  "karla",
  "katherin",
  "kelvin",
  "kevin",
  // ── L ──────────────────────────────────────────────────────────────────
  "laura",
  "lautaro",
  "lazaro",
  "leandro",
  "leonardo",
  "leonel",
  "leonor",
  "leticia",
  "liliana",
  "lisandra",
  "lisbeth",
  "lizbeth",
  "lizmarie",
  "lorena",
  "lorenzo",
  "lourdes",
  "lucas",
  "lucia",
  "luis",
  "luis alberto",
  "luisa",
  "lupita",
  "luz",
  // ── M ──────────────────────────────────────────────────────────────────
  "macarena",
  "magdalena",
  "malena",
  "manuel",
  "manuela",
  "marcela",
  "marcelo",
  "marco",
  "marcos",
  "margarita",
  "margarito",
  "maria",
  "maria alejandra",
  "maria fernanda",
  "maria jose",
  "marian",
  "mariana",
  "maribel",
  "marie",
  "mariela",
  "marielis",
  "mario",
  "marisela",
  "marisol",
  "maritza",
  "mark",
  "marleny",
  "marta",
  "martha",
  "martin",
  "martina",
  "marvin",
  "massiel",
  "mateo",
  "matias",
  "mauricio",
  "mauro",
  "maximiliano",
  "maximino",
  "mayra",
  "melissa",
  "melvin",
  "mercedes",
  "micaela",
  "michael",
  "michelle",
  "miguel",
  "miguel angel",
  "milagros",
  "miriam",
  "misael",
  "moises",
  "monica",
  // ── N ──────────────────────────────────────────────────────────────────
  "nahomy",
  "naomi",
  "natalia",
  "nathaly",
  "nayeli",
  "nelson",
  "nery",
  "nicolas",
  "nicole",
  "noe",
  "noel",
  "noely",
  "noemi",
  "norma",
  // ── O ──────────────────────────────────────────────────────────────────
  "octavio",
  "olivia",
  "omar",
  "oralia",
  "orlando",
  "orvin",
  "oscar",
  "osman",
  "osmany",
  "oswaldo",
  // ── P ──────────────────────────────────────────────────────────────────
  "pablo",
  "paola",
  "patricia",
  "paul",
  "paula",
  "pedro",
  "peter",
  "pilar",
  "porfirio",
  // ── R ──────────────────────────────────────────────────────────────────
  "rafael",
  "ralph",
  "ramiro",
  "ramon",
  "raul",
  "raymond",
  "raymundo",
  "rebeca",
  "regina",
  "reinaldo",
  "remedios",
  "renata",
  "renato",
  "rene",
  "reynaldo",
  "ricardo",
  "richard",
  "rigoberto",
  "robert",
  "roberto",
  "rocio",
  "rodolfo",
  "rodrigo",
  "rolando",
  "ronald",
  "rony",
  "rosa",
  "rosalia",
  "rosanna",
  "rosario",
  "rosendo",
  "rosmery",
  "roxana",
  "ruben",
  "ruth",
  // ── S ──────────────────────────────────────────────────────────────────
  "salvador",
  "samuel",
  "sandra",
  "sandy",
  "santiago",
  "saul",
  "sebastian",
  "selvin",
  "sergio",
  "shaira",
  "silvia",
  "simon",
  "socorro",
  "sofia",
  "soledad",
  "sonia",
  "steven",
  "stiven",
  "sulma",
  // ── T ──────────────────────────────────────────────────────────────────
  "tamara",
  "teresa",
  "thiago",
  "tomas",
  "trinidad",
  // ── U ──────────────────────────────────────────────────────────────────
  "ulises",
  "uriel",
  // ── V ──────────────────────────────────────────────────────────────────
  "valentin",
  "valentina",
  "valentino",
  "valeria",
  "vanesa",
  "vanessa",
  "veronica",
  "vicente",
  "victor",
  "victoria",
  "vidal",
  "virginia",
  // ── W ──────────────────────────────────────────────────────────────────
  "walter",
  "wanda",
  "wendy",
  "wilfredo",
  "william",
  "wilmary",
  "wilmer",
  "wilton",
  // ── X ──────────────────────────────────────────────────────────────────
  "ximena",
  "xiomara",
  "xochitl",
  // ── Y ──────────────────────────────────────────────────────────────────
  "yadier",
  "yadira",
  "yamilet",
  "yamileth",
  "yandel",
  "yanelis",
  "yaretzi",
  "yaritza",
  "yeison",
  "yency",
  "yesenia",
  "yessenia",
  "yoan",
  "yoel",
  "yoelvis",
  "yolanda",
  "yordan",
  "yuliana",
  "yunaisy",
  "yuniesky",
  "yunior",
  // ── Z ──────────────────────────────────────────────────────────────────
  "zuleika",
  // ── Central America – names common in Guatemala, Honduras, El Salvador,
  //    Nicaragua, Costa Rica & Panama but under-represented above ──────────
  // Audited against top-20 male/female given names per country (INE/national
  // registry data, 2020–2024). Names already present in the main A-Z section
  // were excluded; only net-new entries are listed here.
  // Male
  "bayardo",
  "eliecer",
  "fabricio",
  "mynor",
  "otto",
  "roger",
  "wilber",
  // Female
  "flor",
  "griselda",
  "ingrid",
  "iris",
  "kimberly",
  "krissia",
  // ── Caribbean – names common in Cuba, Dominican Republic & Puerto Rico
  //    but under-represented above ─────────────────────────────────────────
  // Audited against top-20 male/female given names per country (ONEC/ONE/
  // Estado Libre Asociado census data, 2020–2024). Net-new entries only.
  // Male
  "ariel",
  "domingo",
  "leinier",
  "livan",
  "yosvany",
  "yunier",
  // Female
  "altagracia",
  "dayami",
  "dulce",
  "gretel",
  "ileana",
  "kenia",
  "odalis",
  "yordanka",
  // ── South America – Paraguay, Bolivia & Ecuador sub-regional names ────────
  // Audited against top-20 male/female given names per country (DGEEC/INE/
  // INEC registry data, 2020–2024). Net-new entries only; names already
  // present in the main A–Z section or Central America block were excluded.
  // Paraguay – Guaraní-influenced and locally common given names
  // Male
  "arnaldo",
  "dionisio",
  "wilberto",
  // Female
  "carina",
  "gladys",
  "mirna",
  "noelia",
  "ramona",
  "zunilda",
  // Bolivia – names common in Andean / indigenous-heritage communities
  // Male
  "willy",
  // Female
  "lidia",
  "nadia",
  // Ecuador – names common in coastal and highland Ecuador
  // Male
  "jefferson",
  "jhonatan",
  // Female
  "estefania",
  "pamela",
  "stephanie",
  "tatiana",
  "viviana",
  // ── PT/BR – distinctly Brazilian / Portuguese given names ───────────────
  // Male
  "caio",
  "fabio",
  "flavio",
  "henrique",
  "igor",
  "joao",
  "mateus",
  "matheus",
  "tiago",
  "vinicius",
  // Female
  "alessandra",
  "aline",
  "bruna",
  "carla",
  "debora",
  "juliana",
  "larissa",
  "luciana",
  "priscila",
  "rafaela",
  "tatiane",
  "viviane",
];

const normalize = (raw: string[]): string[] =>
  Array.from(new Set(raw.map((n) => n.trim().toLowerCase()))).sort();

export const HISPANIC_LAST_NAMES: string[] = normalize(RAW_HISPANIC_LAST_NAMES);
export const HISPANIC_FIRST_NAMES: string[] = normalize(RAW_HISPANIC_FIRST_NAMES);

// Maps common anglicized / English first-name forms to their Hispanic equivalents.
// Values must exist in HISPANIC_FIRST_NAMES for the bridge to award points.
export const ANGLICIZED_FIRST_NAME_MAP: Record<string, string> = {
  // A
  "adam":        "adan",
  "al":          "alberto",
  "alex":        "alejandro",
  "alexander":   "alejandro",
  "alfred":      "alfredo",
  "andy":        "andres",
  "anthony":     "antonio",
  "art":         "arturo",
  "arthur":      "arturo",
  // B
  "bill":        "guillermo",
  "billy":       "guillermo",
  "bob":         "roberto",
  "bobby":       "roberto",
  // C
  "charlie":     "carlos",
  "charles":     "carlos",
  "chris":       "cristobal",
  "christopher": "cristobal",
  "chuck":       "carlos",
  // D
  "dan":         "daniel",
  "danny":       "daniel",
  // E
  "ed":          "eduardo",
  "eddie":       "eduardo",
  "eli":         "elias",
  "ernie":       "ernesto",
  "ernest":      "ernesto",
  // F
  "frank":       "francisco",
  "francis":     "francisco",
  "fred":        "alfredo",
  "freddy":      "alfredo",
  // G
  "gabe":        "gabriel",
  "george":      "jorge",
  "gerard":      "gerardo",
  "jerry":       "gerardo",
  "jim":         "jaime",
  "jimmy":       "jaime",
  "joe":         "jose",
  "joey":        "jose",
  "john":        "juan",
  "johnny":      "juan",
  "jon":         "juan",
  "joseph":      "jose",
  // H
  "hank":        "enrique",
  "henry":       "enrique",
  // L
  "lewis":       "luis",
  "louis":       "luis",
  // M
  "mark":        "marcos",
  "mary":        "maria",
  "matt":        "mateo",
  "matthew":     "mateo",
  "michael":     "miguel",
  "mike":        "miguel",
  "micky":       "miguel",
  // N
  "nick":        "nicolas",
  "nicholas":    "nicolas",
  // P
  "paul":        "pablo",
  "pete":        "pedro",
  "peter":       "pedro",
  // R
  "ralph":       "rafael",
  "ray":         "ramon",
  "raymond":     "ramon",
  "rick":        "ricardo",
  "ricky":       "ricardo",
  "rob":         "roberto",
  "richard":     "ricardo",
  // S
  "sam":         "samuel",
  "simon":       "simon",
  "steve":       "esteban",
  "steven":      "esteban",
  "stephen":     "esteban",
  // T
  "tom":         "tomas",
  "tommy":       "tomas",
  "thomas":      "tomas",
  "tony":        "antonio",
  // V
  "vince":       "vicente",
  "vincent":     "vicente",
  // W
  "will":        "guillermo",
  "willie":      "guillermo",
  "william":     "guillermo",
};
