// Hispanic/Latino name lists for the marketplace name precheck.
//
// SCORING
//   - Recognized Hispanic surname: +70 pts  (passes the ≥ 70 threshold alone)
//   - Recognized Hispanic first name: +25 pts
//   - Score is capped at 100
//   - spanishOutreachRecommended = score >= 70
//
// HOW TO ADD ENTRIES
//   Add to the raw arrays below in any order, any case, with or without accents.
//   The exported constants are automatically deduplicated, lowercased, accent-stripped,
//   and alphabetically sorted at module load time.
//   Use the normalized (accent-free) form when possible — e.g. "perez" not "Pérez".

const RAW_HISPANIC_LAST_NAMES: string[] = [
  // ── A ──────────────────────────────────────────────────────────────────────
  "acosta",
  "aguilar",
  "aguirre",
  "alvarado",
  "alvarez",
  "arenas",
  "arroyo",
  "avila",
  "ayala",
  // ── B ──────────────────────────────────────────────────────────────────────
  "barrera",
  "bautista",
  "bernal",
  "blanco",
  "bustos",
  // ── C ──────────────────────────────────────────────────────────────────────
  "cabrera",
  "calderon",
  "camacho",
  "campos",
  "cardenas",
  "carrillo",
  "castellanos",
  "castillo",
  "castro",
  "cervantes",
  "chavez",
  "cisneros",
  "contreras",
  "cordova",
  "coronado",
  "cortez",
  "cruz",
  "cuevas",
  // ── D ──────────────────────────────────────────────────────────────────────
  "delgado",
  "diaz",
  "dominguez",
  "duarte",
  // ── E ──────────────────────────────────────────────────────────────────────
  "elizondo",
  "enriquez",
  "escamilla",
  "escobar",
  "espinoza",
  "estrada",
  // ── F ──────────────────────────────────────────────────────────────────────
  "figueroa",
  "flores",
  "franco",
  "fuentes",
  // ── G ──────────────────────────────────────────────────────────────────────
  "galindo",
  "galvan",
  "garcia",
  "gomez",
  "gonzalez",
  "guerrero",
  "gutierrez",
  "guzman",
  // ── H ──────────────────────────────────────────────────────────────────────
  "henriquez",
  "herrera",
  // ── I ──────────────────────────────────────────────────────────────────────
  "ibarra",
  // ── J ──────────────────────────────────────────────────────────────────────
  "jimenez",
  "juarez",
  // ── L ──────────────────────────────────────────────────────────────────────
  "leal",
  "leiva",
  "leon",
  "lopez",
  "lozano",
  "luna",
  // ── M ──────────────────────────────────────────────────────────────────────
  "macias",
  "maldonado",
  "martinez",
  "medina",
  "mejia",
  "mendez",
  "mendoza",
  "meza",
  "miranda",
  "molina",
  "montoya",
  "mora",
  "morales",
  "moreno",
  "munoz",
  // ── N ──────────────────────────────────────────────────────────────────────
  "nava",
  "navarrete",
  "navarro",
  "nunez",
  // ── O ──────────────────────────────────────────────────────────────────────
  "ojeda",
  "orozco",
  "ortega",
  "ortiz",
  // ── P ──────────────────────────────────────────────────────────────────────
  "pacheco",
  "padilla",
  "palacios",
  "palomino",
  "paredes",
  "pena",
  "perez",
  "ponce",
  "portillo",
  // ── Q ──────────────────────────────────────────────────────────────────────
  "quiroz",
  // ── R ──────────────────────────────────────────────────────────────────────
  "ramirez",
  "ramos",
  "renteria",
  "reyes",
  "reyna",
  "rincon",
  "rios",
  "rivas",
  "rivera",
  "rodriguez",
  "rojas",
  "roman",
  "rosales",
  "rubio",
  "ruiz",
  // ── S ──────────────────────────────────────────────────────────────────────
  "salazar",
  "salcedo",
  "sanchez",
  "sandoval",
  "santiago",
  "serrano",
  "silva",
  "solis",
  "soriano",
  "soto",
  "suarez",
  // ── T ──────────────────────────────────────────────────────────────────────
  "tapia",
  "tejeda",
  "terrazas",
  "torres",
  "trejo",
  "trujillo",
  // ── V ──────────────────────────────────────────────────────────────────────
  "valdez",
  "valenzuela",
  "vargas",
  "vasquez",
  "vega",
  "velarde",
  "velasquez",
  "vera",
  "vergara",
  "villa",
  "villalobos",
  // ── Z ──────────────────────────────────────────────────────────────────────
  "zamora",
  "zapata",
  "zarate",
  "zelaya",
  "zuniga",
];

const RAW_HISPANIC_FIRST_NAMES: string[] = [
  "adriana",
  "alejandra",
  "alejandro",
  "alfredo",
  "alicia",
  "andrea",
  "andres",
  "angela",
  "antonio",
  "arturo",
  "beatriz",
  "blanca",
  "carlos",
  "carolina",
  "claudia",
  "cristian",
  "daniela",
  "diana",
  "eduardo",
  "elena",
  "enrique",
  "esperanza",
  "fernanda",
  "fernando",
  "francisco",
  "gabriela",
  "guadalupe",
  "guillermo",
  "gustavo",
  "hector",
  "isabel",
  "ivan",
  "javier",
  "jorge",
  "jose",
  "juan",
  "julia",
  "laura",
  "leticia",
  "liliana",
  "lucia",
  "luis",
  "manuel",
  "margarita",
  "maria",
  "mario",
  "martha",
  "miguel",
  "monica",
  "natalia",
  "oscar",
  "pablo",
  "patricia",
  "pedro",
  "rafael",
  "raul",
  "ricardo",
  "roberto",
  "rosa",
  "samuel",
  "sebastian",
  "sergio",
  "silvia",
  "sofia",
  "valentina",
  "veronica",
  "yolanda",
];

const normalize = (raw: string[]): string[] =>
  Array.from(new Set(raw.map((n) => n.trim().toLowerCase()))).sort();

export const HISPANIC_LAST_NAMES: string[] = normalize(RAW_HISPANIC_LAST_NAMES);
export const HISPANIC_FIRST_NAMES: string[] = normalize(RAW_HISPANIC_FIRST_NAMES);
